
# generated by: jx gitops variables
export APP_NAME='jx3-msa-01'
export BRANCH_NAME='master'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='docker.io'
export DOCKER_REGISTRY_ORG='chanmi910'
export DOMAIN='35.186.254.131.nip.io'
export GIT_BRANCH='master'
export JX_CHART_REPOSITORY='http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='docker.io/chanmi910/jx3-msa-01:'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='docker.io'
export REPO_NAME='jx3-msa-01'
export REPO_OWNER='chanmi910'


# content from git...
export JX_PREVIEW_SERVICE="preview-svc"
export JX_PREVIEW_PATH="/preview"


